export const CATEGORIES = [
	"Arts, entertainment and recreation",
	"Beauty, hairdressing, wellness, sports or fitness",
	"Building trades, repairs or installation",
	"Cleaning, security, office admin or other support services",
	"Community or social enterprise",
	"Consultant, contractor or specialist",
	"Design, branding, creative or marketing",
	"Education",
	"Farming, agriculture or working with animals",
	"Gardener or landscape service",
	"Hotel, B&B, bar, restaurant or catering",
	"Human health and social work activities",
	"IT and software development",
	"Importer/Exporter",
	"Maintenance, service and repair of vehicles",
	"Manufacturer",
	"Offline retail",
	"Online retail",
	"Real estate activities",
	"TV, film, advertising, media, publishing or communications",
	"Takeaway",
	"Transportation and storage",
	"Travel agency activities",
	"Wholesale"
];
